Use control requests for updating the bootloader
particle-iot/particle-cli pull request #623
Opened 2022-06-21 14:37 UTC by sergeuz

## Description

## How to Test

## Related Issues / Discussions

## Completeness

- [x] User is totes amazing for contributing!
- [ ] Contributor has signed [CLA](https://docs.google.com/a/particle.io/forms/d/1_2P-vRKGUFg5bmpcKLHO_qNZWGi5HKYnfrrkd-sbZoA/viewform)
- [ ] Problem and solution clearly stated
- [ ] Tests have been provided
- [ ] Docs have been updated
- [ ] CI is passing

2022-06-23 20:50 UTC, monkbroc commented
`particle update` is the main method to bring devices that are running old versions of Device OS up to date. I think the upgrade path proposed won't work on Device OS versions that don't support control requests.

I tested with an Electron running Device OS 1.0.1 that was running some unknown application in DFU mode, and the device went back to normal mode and eventually the CLI gave a timeout.
```
$ particle update

> Your device is ready for a system update.
> This process may take a few minutes. Here it goes!

! An error occurred while attempting to update the system firmware of your device:

TimeoutError: Request timeout

> Please visit our community forums for help with this error:
https://community.particle.io/
```

```
particle serial inspect

Platform: 10 - Electron
Modules
  Bootloader module #0 - version 201, main location, 16384 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
  System module #1 - version 1002, main location, 131072 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
      System module #3 - version 1002
  System module #2 - version 1002, main location, 131072 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
      System module #1 - version 1002
      Bootloader module #0 - version 201
  System module #3 - version 1002, main location, 131072 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
      System module #2 - version 110
  User module #1 - version 5, main location, 131072 bytes max size
    UUID: 2FBE7D89911634323A38F8D56E26F16F75DFAA7D51F0D2C889B6464F69E84998
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
      System module #2 - version 1002
  empty - factory location, 131072 bytes max size
```

Sergey, is there a path forward to ensure that older devices can be upgraded? Is flashing the bootloader first mandatory?

2022-06-23 20:56 UTC, monkbroc commented
I tried with the same Electron in listening mode. The first time the LED changed to magenta and the CLI hung forever until I unplugged the USB cable then I got `UsbError: IN control transfer failed`. I plugged the device back and put it in listening mode and the second time the CLI exited right away with `UsbError: OUT control transfer failed`.

With the device in normal mode I get `TimeoutError: Request timeout`

2022-06-23 21:15 UTC, monkbroc commented
For a fresh out of the box Argon, the CLI exits right away with `No devices found` due to an issue with the serial port not being configured properly in an older 0.8.0-rc (I can't remember which one).

2022-06-23 21:18 UTC, monkbroc commented
Putting the system firmware first in `settings.js` made the `particle update` work for my Electron 1.0.1 and both of my old Argons on 0.8.0-rc.X.

2022-06-23 21:19 UTC, monkbroc requested changes
The approach is not reliable enough to replace `particle update` but worked well when the bootloader was flashed last.

2022-06-24 07:16 UTC, sergeuz commented
> Is flashing the bootloader first mandatory?

@monkbroc The rationale was that flashing it first is _safer_ as we've had issues in the past caused by various incompatibilities between old bootloader and newer system part modules. That's also how devices are updated OTA, so when we introduce changes in Device OS that affect both the bootloader and system firmware, it's assumed that the bootloader will be updated first.

I thought that early Gen 3 devices that come with 0.8.0-rc.X flashed on them still need to be updated using the mobile apps first, but if the CLI has to support updating those devices too, reversing the order is the way to go :+1:

2022-06-24 13:33 UTC, sergeuz commented
@monkbroc Could you give the last [patch](https://github.com/particle-iot/particle-cli/pull/623/commits/fa077429be4380dfc22063f4d3fdc1d26d7b22c5) a try? I tested it with an Argon running 0.8.0-rc.13 (IIRC, that was the first manufacturing release for Gen 3) and an Electron running 0.5.4 and it worked fine.

The logic is the following:

- If the device is in DFU mode when `particle update` is executed, the modules that need to be flashed to the device are reordered so that the modules that can be flashed via DFU are flashed first. That ensures that the device will have an updated system firmware before we attempt to flash the remaining modules via control requests. 
- If the device is not in DFU mode and is running an older version of Device OS than 2.0.0, we fail and suggest the user to switch the device into DFU mode.
- Devices running Device OS 2.0.0 and higher are flashed following the original logic from this PR.

2022-06-24 15:37 UTC, monkbroc approved these changes
The new approach worked for me. I'm approving the PR. I'd like Mirande to take a look as well next week when he's back before this is merged and released.

2022-06-24 15:37 UTC, monkbroc commented on src/cmd/update.js
> +			console.log(chalk.red('!'), 'The version of Device OS that is running on the device is too old.');
It's not necessary to give this information to the user. The next line (please switch to DFU) is sufficient.

2022-06-29 16:35 UTC, busticated reviewed
awesome thanks @sergeuz 🙏 

i'm seeing some weirdness in the `e2e` tests but i'm still poking around + testing here

2022-06-30 09:43 UTC, sergeuz commented on package.json
> +    "@particle/device-constants": "^1.8.0-rc.0",
Yeah, I planned to publish the changes from [device-constants/#22](https://github.com/particle-iot-inc/device-constants/pull/22) first and then update it here. Could you give that PR a look as well?

2022-06-30 17:11 UTC, busticated commented
i'm seeing a bunch of failures running the `e2e` tests locally with a device connected. seems like these steps are no longer working as expected (timing out for some reason):

https://github.com/particle-iot/particle-cli/blob/control-req-update/sc-104580/test/e2e/flash.e2e.js#L45-L46

i'm running `npm run test:e2e -- --grep="Flash Commands"` - are others able to run those successfully? 

fwiw, my device info below:

<details>
<summary><b>`particle serial inspect` output</b></summary>
<p>

```
Platform: 12 - Argon
Modules
  Bootloader module #0 - version 1006, main location, 49152 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
  System module #1 - version 2301, main location, 671744 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
      Bootloader module #0 - version 1005
      Radio stack module #0 - version 202
  User module #1 - version 6, main location, 131072 bytes max size
    UUID: 6EDEE61AAF0801707C245DBBB97973588BAE77A8127A210FE5A7A278AB812C0A
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
      System module #1 - version 2301
  NCP module #0 - version 5, main location, 1536000 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
  Radio stack module #0 - version 202, main location, 192512 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
```

</p>
</details>

2022-07-01 08:56 UTC, sergeuz commented
> i'm running npm run test:e2e -- --grep="Flash Commands" - are others able to run those successfully?

Oops, I forgot to change the hardcoded device name in one of those tests. The tests pass for me reliably though on an Argon running the same firmware as yours :shrug: The code paths of the `flash` and `usb` commands are largely unchanged in this PR, so I'm puzzled as to what might be causing the problem in your case.

2022-07-01 17:03 UTC, busticated commented
@sergeuz more info on my `e2e` issues. seems i'm hitting errors trying to query for cloud status after resetting the device.

the command (`particle usb cloud-status <device-id> --until connected`) basically loops recursively ignoring errors until it either gets the expected status or times-out. when i log out debug info i see a series of errors like:

```
The device should not be in DFU mode
Failed to set alt setting
Missing permissions to access the USB device
Failed to claim interface
Unable to open USB device
Unable to connect to the device <id>. Make sure the device is connected to the host computer via USB
Unable to open USB device
Unable to enumerate USB devices
```

>The tests pass for me reliably though on an Argon running the same firmware as yours

ah, ok great. that seems a stronger hint that something is weird in my local env. i'll keep an eye on it but i think this is good to ship.

edit: ah, CI is now flaking out w/ `failed to create host: Image xcode:13 is not supported` - i'll get a PR up for that ASAP as it'll block releasing :+1:

2022-07-01 21:27 UTC, busticated approved these changes

2022-07-04 14:36 UTC, sergeuz commented
> seems i'm hitting errors trying to query for cloud status after resetting the device.

@busticated Do those tests pass in `master` for you?

> CI is now flaking out w/ failed to create host: Image xcode:13 is not supported - i'll get a PR up for that ASAP

Thank you!

2022-07-18 12:13 UTC, sergeuz commented
@busticated Do you see the same issue in `master` or is it only reproducible with this branch for you?

2022-07-18 23:25 UTC, busticated commented
@sergeuz i went back and tested previous versions - the issue reproduces just by running `npm run test:e2e -- --grep="USB DFU Subcommand" --bail` - some more info:

* `v3.2.0`: fail (`particle-usb@2.0.0` | [source](https://github.com/particle-iot/particle-cli/tree/cbb0b08645a96bbe22d4715c1b502818c55acab6))
* `v3.1.0`: fail (`particle-usb@2.0.0` | [source](https://github.com/particle-iot/particle-cli/tree/aa860e6e2843fe9a0984588c8ecda863983bfc8e))
* `v3.0.0`: fail (`particle-usb@2.0.0` | [source](https://github.com/particle-iot/particle-cli/tree/329a14a4c910cfb2d2d2b323152e732c73321c59)) 
* `v2.16.0`: ok (`particle-usb@1.2.1` | [source](https://github.com/particle-iot/particle-cli/tree/7e642afda6bb0fde65057a00fb3cd0b734aca159)) 

in the case of `v3.1.0`, i saw it pass _once_ but then re-runs failed multiple times. `v2.16.0` passed reliably. so, i guess i have some more digging to do 😅 😬 😞 

i don't think that needs to hold up merging this PR since this issue obviously predates your changes.

thanks for the help 🙏 👍

2022-07-19 11:19 UTC, sergeuz commented
@busticated The only relevant change I noticed between 2.16.0 and 3.0.0 is that we updated particle-usb to 2.0.0 in the latter release :thinking: 

I'm going to merge this PR given that the issue is not new. Let's create a story to investigate it further.

2022-07-19 11:20 UTC, merged